### ISSUE TITLE
Make the Picture to be in the Center of the webpage

### ISSUE THREAD

**Issue by jt4000** [DxF5H/lightbox#3]
Hello!
The position of the picture is not in the height of the center in my personal webpage.

My webpage use jquery and bootstrap v.3
When I have many pictures in a single webpage the looks of it is below:
![p1](https://cloud.githubusercontent.com/assets/14993569/22245560/cf3dc686-e230-11e6-9a8a-fa30995d2693.png)

When I have a single picture in a single webpage, it looks like this
![p2](https://cloud.githubusercontent.com/assets/14993569/22245578/e1644d58-e230-11e6-91f5-dc21872450a1.png)

However, 
WHen I made a sample with simplified code and pictures, I cannot retrieve exactly the same result.
The sample is below.

Thank you!

```


<!DOCTYPE html>
<html>
<head>
	<title>Lightbox.js Basic Demo</title>
</head>

<body>

<link rel="stylesheet" href="./Lightbox.js Basic Demo_files/lightbox.css" />




	<a href="http://www.faithbaptistwh.org/wp-content/uploads/2014/02/caught-in-the-candy-300x300.jpg" class="lightbox" title="">
		<img src="http://www.faithbaptistwh.org/wp-content/uploads/2014/02/caught-in-the-candy-300x300.jpg" />
	</a>

	<br />
	
	<a href="http://www.hunterdonhikingclub.org/wp-content/uploads/2013/06/hhc-pic9-ed_edited-1-Rv-100-1000x288.jpg" class="lightbox" title="">
		<img src="http://www.hunterdonhikingclub.org/wp-content/uploads/2013/06/hhc-pic9-ed_edited-1-Rv-100-1000x288.jpg" />
	</a>
	
	<br />
	
	
	<a href="http://www.emo-us.com/wp-content/uploads/2013/04/HF0289-EMO-banner_1000x100.jpg" class="lightbox" title="">
		<img src="http://www.emo-us.com/wp-content/uploads/2013/04/HF0289-EMO-banner_1000x100.jpg" />
	</a>
		<br/>
	
	<a href="http://www.emo-us.com/wp-content/uploads/2013/04/HF0289-EMO-banner_1000x100.jpg" class="lightbox" title="">
		<img width="1200" height="50" src="http://www.emo-us.com/wp-content/uploads/2013/04/HF0289-EMO-banner_1000x100.jpg" />
	</a>	
	
			<br/>

	<a href="https://2.bp.blogspot.com/-OQ_wj5FWmqY/UC-TYphU4pI/AAAAAAAAAds/jUe8AnHTiSo/s1600/50x50.gif" class="lightbox" title="">
		<img src="https://2.bp.blogspot.com/-OQ_wj5FWmqY/UC-TYphU4pI/AAAAAAAAAds/jUe8AnHTiSo/s1600/50x50.gif" />
	</a>	
				<br/>

	<a href="http://www.primocanale.it/img/ADV/1200x50_lig.gif" class="lightbox" title="">
		<img src="http://www.primocanale.it/img/ADV/1200x50_lig.gif" />
	</a>		
	
				<br/>
	
	
	<a href="http://www.loaderplans.com/templates/pfengine/images/pfengineering.jpg" class="lightbox" title="">
		<img src="http://www.loaderplans.com/templates/pfengine/images/pfengineering.jpg" />
	</a>		
	
					<br/>


	<a href="http://www.me.vt.edu/bmdl/wp-content/uploads/sites/17/2015/07/cropped-headerfull.jpg" class="lightbox" title="">
		<img src="http://www.me.vt.edu/bmdl/wp-content/uploads/sites/17/2015/07/cropped-headerfull.jpg" />
	</a>	
	
	
	
	
	
<script src="./Lightbox.js Basic Demo_files/lightbox.js.download"></script>
<script>
    lightbox('.lightbox', {
        captions: true,
        captionsSelector: 'self',
        captionAttribute: 'title',
        nav: false,
        navText: [
            '&lsaquo;',
            '&rsaquo;'
        ],
        close: true,
        closeText: '&times;',
        counter: false,
        keyboard: true,
        zoom: true,
        zoomText: '',
        docClose: true,
        swipeClose: true,
        scroll: false
    });
</script>



</body>
</html>


```

**Comment by DxF5H** [comment]
Hi!

I have fixed the bug. Please download the new files.

**Comment by jt4000** [comment]
I have downloaded the new source code and the bug still is existing.

**Comment by DxF5H** [comment]
Hi!

Have you also download the CSS file? Can you make a CodePen, JsBin or JsFiddle example?
